export const testDataBase = [
  {
    id: 102,
    firstName: 'Sue',
    lastName: 'Corson',
    email: 'DWhalley@in.gov',
    phone: '(612)211-6296',
    address: {
      streetAddress: '9792 Mattis Ct',
      city: 'Waukesha',
      state: 'WI',
      zip: '22178',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 203,
    firstName: 'Jue',
    lastName: 'Dorson',
    email: 'UIhalley@in.gov',
    phone: '(547)211-6296',
    address: {
      streetAddress: '8745 Mattis Ct',
      city: 'Loukesha',
      state: 'SI',
      zip: '428488',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 347,
    firstName: 'Fiete',
    lastName: 'Bjktuedk',
    email: 'LOhalley@in.gov',
    phone: '(715)211-6296',
    address: {
      streetAddress: '8745 Mattis Ct',
      city: 'Uutjkesha',
      state: 'LU',
      zip: '455488',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 907,
    firstName: 'Bjidkejk',
    lastName: 'Bjktuedk',
    email: 'LOhalley@in.gov',
    phone: '(715)211-6296',
    address: {
      streetAddress: '8745 Mattis Ct',
      city: 'Uutjkesha',
      state: 'LU',
      zip: '455488',
    },
    description: 'et lacus magna dolor...',
  },
  {
    id: 807,
    firstName: 'Jkjke',
    lastName: 'Bjktuedk',
    email: 'LOhalley@in.gov',
    phone: '(715)211-6296',
    address: {
      streetAddress: '8745 Mattis Ct',
      city: 'Uutjkesha',
      state: 'LU',
      zip: '455488',
    },
    description: 'et lacus magna dolor...',
  },
]
